### ISSUE TITLE
Font styles aren't working

### ISSUE THREAD

**Issue by krainboltgreene** [jxnblk/cxs#55]
Here's the DOM node:

``` html
<h1 data-component="Heading" data-kind="page" class="ff-'Handlee'__cursive">Lacqueristas</h1>
```

Here's the styling sheet per Chrome:

``` css
element.style {
}
@media (min-width: 550px)
h1 {
  font-size: 5.0rem;
}
h1 {
  font-size: 4.0rem;
  line-height: 1.2;
  letter-spacing: -.1rem;
}
h1, h2, h3, h4, h5, h6 {
  margin-top: 0;
  margin-bottom: 2rem;
  font-weight: 300;
}
h1 {
  font-size: 2em;
  margin: 0.67em 0;
}
```

Here's the style object:

``` javascript
const headingsStyle = {
  page: {fontFamily: "'Handlee', cursive"},
}
```

Here's the static CSS generated server side:

``` css
.ff-'Handlee'__cursive {
  font-family: 'Handlee', cursive
}
```
